replicaCount: 1

image:
  repository: harbor.clairvoyant.proj.nro.ic.gov/ask-francis/pulse-rag
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: francis-harbor

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  type: ClusterIP
  portWeb: 8000

resources:
  requests:
    cpu: "2"
    memory: "4Gi"
  limits:
    cpu: "4"
    memory: "8Gi"

ingress:
  enabled: true
  className: "askfrancis-nginx"
  annotations:
    argocd.argoproj.io/tracking-id: report-rollup:networking.k8s.io/Ingress:cosmichorizon/report-rollup
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/report-rollup)$ $1/ permanent;
    external-dns.alpha.kubernetes.io/target: pulse-rag.clairvoyant.proj.nro.ic.gov

  hosts:
    - host: pulse-rag.clairvoyant.proj.nro.ic.gov
      paths:
        - path: /report-rollup(/|$)(.*)
          pathType: ImplementationSpecific
          backendPort: 8000

  tls: []
