apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "report-rollup.fullname" . }}
  labels:
    {{- include "report-rollup.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "report-rollup.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "report-rollup.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.portWeb }}
              protocol: TCP
          volumeMounts:
            - name: cosmic-certs
              mountPath: /etc/certs
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: cosmic-certs
          secret:
            secretName: cosmic-secret
