import os
from pathlib import Path
from dotenv import load_dotenv
import chromadb
from chromadb.api.types import EmbeddingFunction, Documents, Embeddings
from pir_search.llm import call_llm
from rich.console import Console

from pir_search.models import Article
from pir_search.extractor import get_spacy_model
from pir_search.embedder import get_nomic_model, embed_query

load_dotenv()
console = Console()

class NomicChromaEmbeddingFunction(EmbeddingFunction):
    """
    Custom embedding function for ChromaDB that uses our loaded Nomic model
    and applies the document retrieval instruction prefix.
    """
    def __call__(self, input: Documents) -> Embeddings:
        model = get_nomic_model()
        prefixed = [f"search_document: {doc}" for doc in input]
        embeddings = model.encode(prefixed, batch_size=32, normalize_embeddings=True)
        return embeddings.tolist()

# Global Chroma client and collection configuration
CHROMA_PATH = Path("./chroma_store")

def get_chroma_collection():
    """Initializes the Chroma persistent client and gets or creates the weekly_articles collection."""
    ef = NomicChromaEmbeddingFunction()
    client = chromadb.PersistentClient(path=str(CHROMA_PATH.resolve()))
    return client.get_or_create_collection("weekly_articles", embedding_function=ef)

def chunk_article_text(text: str, target_chunk_tokens: int = 512) -> list[str]:
    """
    Splits the article full_text into sentence-bounded chunks of ~512 tokens.
    Uses spaCy for robust sentence boundary detection.
    """
    nlp = get_spacy_model()
    doc = nlp(text)
    # Collect sentences
    sentences = [sent.text.strip() for sent in doc.sents if sent.text.strip()]

    chunks = []
    current_chunk = []
    current_tokens = 0

    for sent in sentences:
        # Heuristic: 1 word ≈ 1.3 tokens for typical English text
        word_count = len(sent.split())
        est_tokens = int(word_count * 1.3) + 2

        if current_tokens + est_tokens > target_chunk_tokens and current_chunk:
            chunks.append(" ".join(current_chunk))
            current_chunk = [sent]
            current_tokens = est_tokens
        else:
            current_chunk.append(sent)
            current_tokens += est_tokens

    if current_chunk:
        chunks.append(" ".join(current_chunk))

    return chunks

def ingest_articles(articles: list[Article]) -> None:
    """
    Chunks the full_text of all input articles, generates Nomic embeddings,
    and upserts them into the local ChromaDB collection.
    """
    if not articles:
        return

    console.print(f"[blue]Ingesting {len(articles)} articles into ChromaDB...[/blue]")
    collection = get_chroma_collection()

    ids = []
    documents = []
    metadatas = []

    for art in articles:
        chunks = chunk_article_text(art.full_text)
        for idx, chunk in enumerate(chunks):
            chunk_id = f"{art.article_id}_chunk_{idx}"
            ids.append(chunk_id)
            documents.append(chunk)
            metadatas.append({
                "article_id": art.article_id,
                "title": art.title,
                "url": art.url,
                "chunk_index": idx
            })

    # ChromaDB upsert (overwrites if ID exists)
    collection.upsert(
        ids=ids,
        documents=documents,
        metadatas=metadatas
    )
    console.print(f"[green]Successfully ingested {len(ids)} document chunks into ChromaDB.[/green]")

def generate_mock_rag_answer(question: str, original_report: str, chunks: list[str], metadatas: list[dict]) -> str:
    """Generates a structured simulated RAG follow-up answer."""
    findings = []
    for chunk, meta in zip(chunks, metadatas):
        # Extract a short preview or relevant sentence
        preview = chunk[:250] + "..." if len(chunk) > 250 else chunk
        findings.append(f"**From source [{meta['article_id']}] ({meta['title']}):**\n> {preview}")

    joined_findings = "\n\n".join(findings)

    return f"""### Follow-up Assessment
Regarding the query: *"{question}"*

Based on the relevant documents retrieved from the collection, here are the detailed points:

{joined_findings}

### Key Source References
{", ".join(f"[{m['article_id']}]" for m in metadatas)}

*Note: This is a simulated answer generated by the offline local RAG fallback engine. To enable real Claude answers, configure your ANTHROPIC_API_KEY in .env.*"""

def query_rag(question: str, original_report: str) -> str:
    """
    Queries the ChromaDB collection using Nomic semantic search.
    Presents the top-8 chunks along with the original report to Claude to answer the user's follow-up.
    Falls back to a local structured compiler if ANTHROPIC_API_KEY is not set.
    """
    collection = get_chroma_collection()

    # 1. Asymmetric semantic query: embed the query with the Nomic query prefix
    q_emb = embed_query(question)
    
    # Query ChromaDB using the manually generated embedding
    results = collection.query(
        query_embeddings=[q_emb[0].tolist()],
        n_results=8
    )

    # Extract retrieved chunks
    chunks = results.get("documents", [[]])[0]
    metadatas = results.get("metadatas", [[]])[0]

    if not chunks:
        return "No relevant context was found in the article database to answer your follow-up query."

    # 2. Check for Sanctuary / Anthropic API Key
    sanctuary_key = os.getenv("SANCTUARY_KEY")
    anthropic_key = os.getenv("ANTHROPIC_API_KEY")
    if (not sanctuary_key or not sanctuary_key.strip()) and (not anthropic_key or not anthropic_key.strip()):
        console.print("[yellow]WARNING: Neither SANCTUARY_KEY nor ANTHROPIC_API_KEY is set. Using Mock RAG answer compiler.[/yellow]")
        return generate_mock_rag_answer(question, original_report, chunks, metadatas)

    # 3. Call Claude with context via Sanctuary
    try:
        console.print("[blue]Querying Sanctuary for grounded follow-up...[/blue]")
        
        context_str = "\n\n".join(
            f"Source [{meta['article_id']}]: {meta['title']}\n{doc}"
            for doc, meta in zip(chunks, metadatas)
        )
        
        system_prompt = """You are an intelligence analyst assistant. You are answering a follow-up question
        regarding a previously generated intelligence report. You are given the original report and 
        additional context chunks from the source document database.
        Provide an answer that is strictly grounded in the provided context and the original report.
        Cite sources using [ID] notation (e.g. [ART001]) when answering. If the context does not contain the answer,
        state that you cannot answer based on current intelligence."""
        
        user_prompt = f"""Original Report:
{original_report}

---
Retrieved Context:
{context_str}

---
Follow-up Question: {question}
"""
        
        return call_llm(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            model="bedrock-claude-sonnet-4.5-gov",
            max_tokens=1500,
            temperature=0.2
        )
    except Exception as e:
        console.print(f"[red]Error calling Sanctuary API for RAG query: {e}. Falling back to Mock RAG answer.[/red]")
        return generate_mock_rag_answer(question, original_report, chunks, metadatas)
